services:
  database-mysql:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=music-app
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - 3307:3306
    volumes:
      - ../backend:/docker-entrypoint-initdb.d
    expose:
      - 3306

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DB_PORT=3306
      - DB_HOST=database-mysql
      - URL_REACT=http://localhost
    ports:
      - 9000:9000
    depends_on:
      - database-mysql
    expose:
      - 9000

  nginx:
    image: nginx:1.27.4
    container_name: nginx-server
    ports:
      - "8000:80"
    volumes:
      - ../frontend/dist:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
