services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "9000:9000"
    volumes:
      - ../backend:/var/www
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: music-app
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ../backend:/docker-entrypoint-initdb.d
    networks:
      - app-network

  webserver:
    image: nginx:latest
    container_name: nginx-backend
    ports:
      - "8080:80" # Bạn truy cập API ở cổng 8080
    volumes:
      - ../backend:/var/www
      - ./backend/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - app-network

  frontend:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ../frontend/dist:/usr/share/nginx/html
      - ./frontend/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
networks:
  app-network:

volumes:
  dbdata:
